bundle:
    path: src/Loyalty/SeitaBackOfficeBundle
entities:
    path: Entity
    namespace: Loyalty\SeitaBackOfficeBundle\Entity
business:
    path: Business
    namespace: Loyalty\SeitaBackOfficeBundle\Business
    factoryServiceName: seita.business.factory
    headComment: "/**\r\n * Club Seita\r\n * Copyright 2015 - Loyalty Technologies\r\n */"
    generation: 'true'
