bundle:
    path: src/Sebk/DixheureBundle
    replaceRepositories: 'false'
entities:
    path: Entity
    namespace: Sebk\DixheureBundle\Entity
business:
    path: Business
    namespace: Sebk\DixheureBundle\Business
    headComment: "/**\r\n * This file is a part of dixheure\r\n * Copyright 2014 - Sébastien Kus\r\n * Licenced under GNU GPL V3\r\n */"
