parameters:
#    sebk_mysql_to_doctrine.example.class: Sebk\MysqlToDoctrineBundle\Example

services:
    sebk_mysql_to_doctrine.main:
        class: Sebk\MysqlToDoctrineBundle\MysqlToDoctrine\MysqlToDoctrine
        arguments: [@twig, %kernel.root_dir%]
#    sebk_mysql_to_doctrine.example:
#        class: %sebk_mysql_to_doctrine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
